sudo: required
services:
  - docker

before_install:
  - docker build -t jesseokeya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jesseokeya/react-test npm test -- --coverage

after_success:
  - docker build -t jesseokeya/multi-client ./client
  - docker build -t jesseokeya/multi-nginx ./nginx
  - docker build -t jesseokeya/multi-server ./server
  - docker build -t jesseokeya/multi-worker ./worker
# Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push jesseokeya/multi-client 
  - docker push jesseokeya/multi-nginx 
  - docker push jesseokeya/multi-server
  - docker push jesseokeya/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ca-central-1-422815456249
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY