sudo: required
services:
  - docker

before_install:
  - docker build t jesseokeya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jesseokeya/react-test npm test -- --coverage

after_success:
  - docker build -t jesseokeya/multi-client ./client
  - docker build -t jesseokeya/multi-nginx ./nginx
  - docker build -t jesseokeya/multi-server ./server
  - docker build -t jesseokeya/multi-worker ./worker
# Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push jesseokeya/multi-client 
  - docker push jesseokeya/multi-nginx 
  - docker push jesseokeya/multi-server
  - docker push jesseokeya/multi-worker